=head1 NAME

Marpa::HTML::Support - Marpa::HTML Support, and How to Report Bugs

=head1 DESCRIPTION

Marpa::HTML is free software.
There is no warranty.

=head1 BUGS

Please report any bugs or feature requests to
C<bug-marpa-html at rt.cpan.org>, or through the web interface at
L<http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Marpa-HTML>.
I will be notified, and then you'll automatically be notified of progress on
your bug as I make changes.

=head1 SUPPORT

You can find documentation for this module with the perldoc command.

=for Marpa::Display
ignore: 1

    perldoc Marpa::HTML

=for Marpa::Display::End
    
You can also look for information at:

=over 4

=item * AnnoCPAN: Annotated CPAN documentation

L<http://annocpan.org/dist/Marpa-HTML>

=item * CPAN Ratings

L<http://cpanratings.perl.org/d/Marpa-HTML>

=item * RT: CPAN's request tracker

L<http://rt.cpan.org/NoAuth/Bugs.html?Dist=Marpa-HTML>

=item * Search CPAN

L<http://search.cpan.org/dist/Marpa-HTML>

=back

=head1 LICENSE AND COPYRIGHT

Copyright 2007-2010 Jeffrey Kegler, all rights reserved.  Marpa::HTML is free
software under the Perl license.  For details see the LICENSE file in
the Marpa::HTML distribution.
