# Copyright 2011 Jeffrey Kegler
# This file is part of Marpa::XS.  Marpa::XS is free software: you can
# redistribute it and/or modify it under the terms of the GNU Lesser
# General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
#
# Marpa::XS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser
# General Public License along with Marpa::XS.  If not, see
# http://www.gnu.org/licenses/.

=head1 NAME

Marpa::XS - XS extension of Marpa

=head1 SYNOPSIS

=for Marpa::XS::Display
name: Engine Synopsis Unambiguous Parse
normalize-whitespace: 1

    use Marpa::XS;

=for Marpa::XS::Display::End

=head1 DESCRIPTION

=head2 This is ALPHA software

This is B<alpha> software.
There may be bugs. The interface may change.
Please be careful.
Do not rely
on it for anything mission-critical.

=head2 Where is the Documentation?

L<Marpa::XS|http://search.cpan.org/dist/Marpa-PP/>
is the XS extension of
L<Marpa::PP|http://search.cpan.org/dist/Marpa-PP/>.
Usage is the same, and the two modules
share the same documentation.
To avoid duplication,
the documentation is not kept here.
The documentation for both
Marpa::XS and Marpa::PP can be found in the
L<Marpa::PP|http://search.cpan.org/dist/Marpa-PP/>
module.

=head1 SUPPORT

L<Marpa::XS> comes without warranty.
Support is provided
on a volunteer basis 
through the standard mechanisms for CPAN modules.
L<The Support document|Marpa::XS::Support> has details.

=head1 COPYRIGHT AND LICENSE

=for Marpa::XS::Display
ignore: 1

  Copyright 2011 Jeffrey Kegler
  This file is part of Marpa::XS.  Marpa::XS is free software: you can
  redistribute it and/or modify it under the terms of the GNU Lesser
  General Public License as published by the Free Software Foundation,
  either version 3 of the License, or (at your option) any later version.
  
  Marpa::XS is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.
  
  You should have received a copy of the GNU Lesser
  General Public License along with Marpa::XS.  If not, see
  http://www.gnu.org/licenses/.

=for Marpa::XS::Display::End

=cut

# Local Variables:
#   mode: cperl
#   cperl-indent-level: 4
#   fill-column: 100
# End:
# vim: expandtab shiftwidth=4:

