---
abstract: 'High-level HTML Parsing'
author:
  - 'Jeffrey Kegler'
build_requires:
  Test::More: 0.94
configure_requires:
  Module::Build: 0.3601
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Marpa-HTML
no_index:
  directory:
    - inc
    - t
    - author.t
    - save
  namespace:
    - Marpa::HTML::Internal
    - Marpa::HTML::Display::Internal
    - Marpa::HTML::Test
  package:
    - Marpa::HTML::Offset
    - Marpa::HTML::Test
    - Marpa::HTML::Display
    - Marpa::HTML::Internal
provides:
  Marpa::HTML:
    file: lib/Marpa/HTML.pm
    version: 0
recommends:
  Marpa::XS: 0.010000
requires:
  Carp: 1.08
  Data::Dumper: 2.125
  HTML::Parser: 3.64
  HTML::PullParser: 3.57
  List::Util: 1.21
  Marpa::PP: 0.008000
  Scalar::Util: 1.21
  perl: 5.01
resources:
  repository: git://github.com/jeffreykegler/Marpa--HTML.git
version: 0.103_000
