# Copyright 2011 Jeffrey Kegler
# This file is part of Marpa::XS.  Marpa::XS is free software: you can
# redistribute it and/or modify it under the terms of the GNU Lesser
# General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
#
# Marpa::XS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser
# General Public License along with Marpa::XS.  If not, see
# http://www.gnu.org/licenses/.

=head1 NAME

Marpa::XS::Semantics::Order - How Marpa Ranks Ambiguous Parses

=head1 DESCRIPTION

This document details the order in which
the recognizer's
L<C<value>|Marpa::XS::Recognizer/"value">
method
returns parse results.
The same mechanism allows the selection of parse results.
It can also be exploited to do the actual processing
of parses, using side effects.

=head2 Duplicate Parses are Eliminated

In a single parse series,
Marpa will never return the same parse result twice.
Marpa regards two parses as being the same if they are
B<semantic duplicates>.

Two parses are semantic duplicates if
a recursive, top-down evaluation of each
applies
the same rules
in the same order
at the same earleme locations.
When this is the case,
a deterministic semantics will
always produce the same value for both parses --
hence the term "semantic duplicate".
When the Marpa documentation refers to duplicate
parses, it will mean semantic duplicates unless otherwise
stated.

=head2 Default Parse Order

By calling
the recognizer's
L<C<value>|Marpa::XS::Recognizer/"value">
method
repeatedly,
Marpa can produce all the parse results
for a given parse.
The default is for the parse results to be returned
in an arbitrary order.
This corresponds to the "C<none>" value of
L<the recognizer's C<ranking_method>|Marpa::XS::Recognizer/"ranking_method">
named argument.

=head2 A General Approach to Sorting Parses

The most general way to sort Marpa parses is for the application
to take control.
The application can set up the Marpa semantic actions
so that the value of every parse result is a
C<< <rank, true_value> >> duple.
The duples can then be sorted by C<rank>.
Once the resuls are sorted,
the C<rank> element of the duple can be discarded.
(Those familiar with the Schwartzian transform
may note a resemblance.
In Perl,
duples can be implemented as references to arrays of 2 elements.)

The user needs to be careful.
In theory, ambiguity can cause an exponential explosion in the number of results.
In practice, ambiguity tends to get out of hand very easily.
Producing and sorting all the parses can take a very
long time.

=head2 The Constant Ranking Method

In the past,
Marpa supported a simplified approach to sorting parses,
called the Constant Ranking Method.
The Constant Ranking Method was intended to be
flexible enough to handle many, perhaps even most,
practical applications,
but simple enough that Marpa is able to optimize it.

The first implementation of
the Constant Ranking Method had a semantics which
made the rank of a node depend on which of its children
were actually
used in each parse result.
While this is what a user would intuitively expect,
it required the
the ranks of subtrees to be recalculated dynamically,
and partially iterated subtrees to be stored and
regrafted into the tree being parsed.
The code to do this was very complicated
and the efficiency trade-offs
arguable.
The Constant Ranking Method
is currently being simplified.
Until its features settle, its documentation has been removed.

=head1 COPYRIGHT AND LICENSE

=for Marpa::XS::Display
ignore: 1

  Copyright 2011 Jeffrey Kegler
  This file is part of Marpa::XS.  Marpa::XS is free software: you can
  redistribute it and/or modify it under the terms of the GNU Lesser
  General Public License as published by the Free Software Foundation,
  either version 3 of the License, or (at your option) any later version.
  
  Marpa::XS is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.
  
  You should have received a copy of the GNU Lesser
  General Public License along with Marpa::XS.  If not, see
  http://www.gnu.org/licenses/.

=for Marpa::XS::Display::End

=cut

# Local Variables:
#   mode: cperl
#   cperl-indent-level: 4
#   fill-column: 100
# End:
# vim: expandtab shiftwidth=4:
