# Copyright 2013 Jeffrey Kegler
# This file is part of Marpa::R2.  Marpa::R2 is free software: you can
# redistribute it and/or modify it under the terms of the GNU Lesser
# General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
#
# Marpa::R2 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser
# General Public License along with Marpa::R2.  If not, see
# http://www.gnu.org/licenses/.

# DO NOT EDIT THIS FILE DIRECTLY
# It was generated by make_internal_pm.pl
# Timestamp: Mon Jul 29 17:49:26 2013

package Marpa::R2::Internal;

use 5.010;
use strict;
use warnings;
use Carp;

use vars qw($VERSION $STRING_VERSION);
$VERSION        = '2.065_004';
$STRING_VERSION = $VERSION;
$VERSION = eval $VERSION;


package Marpa::R2::HTML::Internal::TDesc;
constant->import( 'TYPE' => 0 );
constant->import( 'START_TOKEN' => 1 );
constant->import( 'END_TOKEN' => 2 );
constant->import( 'VALUE' => 3 );
constant->import( 'RULE_ID' => 4 );

package Marpa::R2::HTML::Internal::Token;
constant->import( 'TOKEN_ID' => 0 );
constant->import( 'TAG_NAME' => 0 );
constant->import( 'TYPE' => 1 );
constant->import( 'LINE' => 2 );
constant->import( 'COL' => 3 );
constant->import( 'COLUMN' => 3 );
constant->import( 'START_OFFSET' => 4 );
constant->import( 'END_OFFSET' => 5 );
constant->import( 'IS_CDATA' => 6 );
constant->import( 'ATTR' => 7 );

1;
