# Copyright 2014 Jeffrey Kegler
# This file is part of Marpa::R2.  Marpa::R2 is free software: you can
# redistribute it and/or modify it under the terms of the GNU Lesser
# General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
#
# Marpa::R2 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser
# General Public License along with Marpa::R2.  If not, see
# http://www.gnu.org/licenses/.

=head1 NAME

Marpa::R2::Semantics::Phases - SLIF recognizer phases

=head1 About this document

This document describes in detail the sequence of events
in the SLIF recognizer.
It serves two purposes.

=over 4

=item *

It gives fuller details of the sequence of events
than is given in the other documents.

=item *

It describes the use of more than one parse series.

=back

Applications will usually
find that the order in which
the SLIF recognizer performs tasks "just works".
But some application will depend on the full detail.
These include

=over 4

=item *

applications which make unusual use of side effects in the semantics; and

=item *

and applications which alter their symbol tables at runtime.

=back

=head1 Parse series

The SLIF recognizer can be run several times on the same
virtual input stream.
Each of these runs is called a B<parse series>.

The first parse series starts with a
call to
the SLIF recognizer's
L<C<read()>
method|Marpa::R2::Scanless::R/"read()">.
A parse series can be ended, and a new
one started,
by calling the SLIF recognizer's
L<C<series_restart()>
method|Marpa::R2::Scanless::R/"series_restart()">.
Destroying the recognizer ends the current parse series.

Most applications will not need to use more than
a single parse series.
But they are useful in some specialized
applications.
Starting a new parse series allows the applications
to change some settings and even,
to some extent, the input.
Specifically.

=over 4

=item *

Once input is read into a SLIF recognizer's
virtual input stream, it is there for the life of the recognizer.
It cannot be "unread".
But during the reading phase of a new parse series,
a recognizer can extend the virtual input stream,
using the recognizer's 
L<C<resume()> method|Marpa::R2::Scanless::R/"resume()">.

=item *

Within a parse series,
the semantics package cannot change.
But you can specify a new semantics package
after starting a new parse series.

=item *

Certain other SLIF recognizer settings can be
changed
after starting a new parse series.
These include the SLIF recognizer's
L<C<end> setting|Marpa::R2::Scanless::R/"end">
and its 
L<C<ranking_method> setting|Marpa::R2::Scanless::R/"ranking_method">.
For details, see
L<Marpa::R2::Scanless::R/"Recognizer settings">.

=back

=head1  Parse trees and parse series

Because Marpa allows ambiguous parsing,
each parse can produce a B<parse series> --
a series of zero or more parse trees,
where each tree its own parse result.
In most applications, there is only
one parse series.
The call to the
L<SLIF recognizer's C<read()>
method|Marpa::R2::Scanless::R/"read()">
is the
start of the first parse series.

The first parse series continues until there is
a call to the
L<C<series_restart()>
method|Marpa::R2::Scanless::R/"series_restart()">
or until the recognizer is destroyed.
Each call of the C<series_restart()> method
starts a new parse series.
An application is usually interested in only one
parse series.

The processing of each parse series takes place
in two phases, the second of which is optional.
The Reading Phase is the first phase,
and starts when then parse series starts.
The Evaluation Phase is optional.
If it occurs,
it comes after the Reading Phase.

=head1 SLIF recognizer phases

A SLIF recognizer is always in one of three phases:

=over 4

=item * The Initial Phase;

=item * a Reading Phase; or

=item * an Evaluation Phase.

=back

Note that,
in this document, phase and subphase names are capitalized.
This is done for clarity.

Reading and Evaluation Phases
are always part of a parse series.
The Initial Phase is never part of any parse series.

=head1 The Initial Phase

The B<Initial Phase> of a SLIF recognizer
begins when the recognizer is created with the
calls the L<C<new()>|"new()"> method.
It ends when
the L<C<read()>|"read()"> method
in called.
It will also end, of course, if
the recognizer is destroyed,
but most applications will want to
continue into the next phases.

There is always exactly one Initial Phase for
every recognizer.
The Initial Phase is not part of any parse series.
Very little can happen in this phase.
It is possible to change some recognizer settings
using the L<C<set()>|"set()"> method.

=head1 The Reading Phase

The Reading Phase starts
when a parse series starts,
that is
with either a call to the
L<C<read()>
method|Marpa::R2::Scanless::R/"read()">
or a call to the
L<C<series_restart()>
method|Marpa::R2::Scanless::R/"series_restart()">.
The reading phase ends when the first of the following occurs:

=over 4

=item *

The recognizer is destroyed.

=item *

A new parse series is begun
by calling the C<series_restart()> method.
This and the previous case are unusual.
Applications almost always
want to continue the parse series into the Evaluation Phase.

=item * The C<value()> method is called for this SLIF recognizer.
This is the most common case.

=back

The C<read()> method can be called only once for a SLIF recognizer.
But, while a Reading Phase continues,
the C<resume()> method may be called multiple times to continue reading
input.
The C<resume()> method should not be called except during the
Reading Phase of a parse series.

A Reading Phase is always part of a parse series.
There is always exactly one Reading Phase for every parse series.

=head1 The Evaluation Phase

The Evaluation Phase begins with a recognizer's first call
to the SLIF's C<value()> method.
It ends when the recognizer is destroyed,
or when
the SLIF's C<series_restart()> method
is called for that recognizer.
The Evaluation Phase is divided into subphases,
as described
L<below|"The evaluation subphases">.
If a parse series ends before the C<value()> method is
called, there is no Evaluation Phase.

If the parse is ambiguous,
the L<C<value()>|"value()"> method
may be called more than once during the evaluation phase.
The second and later calls of
the L<C<value()>|"value()"> method will return
the result of the next parse tree.
When there are no more parse trees,
the L<C<value()>|"value()"> method will return
a Perl C<undef>

If you call
the L<C<resume()>|"resume()"> method
during an Evaluation Phase,
the behavior of
Marpa::R2
is not defined.
You should not do this.

An Evaluation Phase is always part of a parse series,
but it is optional.
A parse series may end without entering into an evalution phase.

=head1 The evaluation subphases

During the evaluation phase of a parse series, we have:

=over 4

=item *

The Parse Series Setup Subphase,
which occurs during during the first call
to the C<value()> method of B<the first> parse series.
It is followed by

=item * the processing of zero or more parse trees.

=back

While processing a parse tree, we have:

=over 4

=item * 

The Parse Tree Setup Subphase,
which occurs during during the first call
to the C<value()> method of B<every> series.
It is followed by

=item * a Parse Tree Traveral Subphase.

=back

B<Node Evaluation Time>
is the Tree Traversal Subphase, as seen from the point of view of
each rule node.  It is not a separate phase.

=head1 Parse Series Setup Subphase

During the Parse Series Setup Subphase
all action names are resolved to
actions --
Perl scalars
or rule evaluation closures.
The rule evaluation closures are not called in the Parse Series Setup Subphase.
They will be called later,
in the Parse Tree Traversal Subphase.
Also, during the Parse Series Setup Subphase,
the logic which
ranks parse trees is executed.

=head1 Parse Tree Setup Subphase

In the Parse Tree Setup Subphase,
the per-parse argument is created.
If a per-parse constructor was found,
it is run at this point, and the per-parse argument is
its return value.
Exactly one Parse Tree Setup Subphase occurs
for each parse tree.

=head1 Parse Tree Traversal Subphase

During the Parse Tree Traversal Subphase,
the rule evaluation closures are called.

=head1 Copyright and License

=for Marpa::R2::Display
ignore: 1

  Copyright 2014 Jeffrey Kegler
  This file is part of Marpa::R2.  Marpa::R2 is free software: you can
  redistribute it and/or modify it under the terms of the GNU Lesser
  General Public License as published by the Free Software Foundation,
  either version 3 of the License, or (at your option) any later version.

  Marpa::R2 is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser
  General Public License along with Marpa::R2.  If not, see
  http://www.gnu.org/licenses/.

=for Marpa::R2::Display::End

=cut

# Local Variables:
#   mode: cperl
#   cperl-indent-level: 4
#   fill-column: 100
# End:
# vim: expandtab shiftwidth=4:
