\input texinfo @c -*-texinfo-*- 
@c %**start of header 
@setfilename api.info 
@settitle libmarpa 0.0.0
@c %**end of header 
@copying 
This manual is for libmarpa, version 0.0.0. 
Copyright @copyright{} 2011 Jeffrey Kegler.
@quotation 
Permission is granted to copy, distribute and/or modify this document 
under the terms of the GNU Free Documentation License, Version 1.2 or 
any later version published by the Free Software Foundation;
@end quotation 
@end copying 
@titlepage 
@title libmarpa
@author Jeffrey Kegler
@c The following two commands 
@c start the copyright page. 
@page 
@vskip 0pt plus 1filll 
@insertcopying

Published by Jeffrey Kegler
@end titlepage 
@c So the toc is printed at the start. 
@contents 
@ifnottex 
@node Top 
@top title 
This manual is for libmarpa, version 0.0.0. 
@end ifnottex 
@menu 
* First Chapter:: One
* Second Chapter:: Two
@end menu 
@node First Chapter 
@chapter First Chapter 
@cindex first chapter 
@cindex chapter, first 

@deftypefun char* glib_check_version
    (int @var{required_major}, int @var{required_minor}, int @var{required_micro})

Checks that the GLib library in use is compatible with the
given version. Generally you would pass in the constants
#GLIB_MAJOR_VERSION, #GLIB_MINOR_VERSION, #GLIB_MICRO_VERSION
as the three arguments to this function; that produces
a check that the library in use is compatible with
the version of GLib the application or module was compiled
against.

Compatibility is defined by two things: first the version
of the running library is newer than the version
@var{required_major}.@var{required_minor}.@var{required_micro}.
Second
the running library must be binary compatible with the
version
@var{required_major}.@var{required_minor}.@var{required_micro}
(same major version.)

Return value: %NULL if the GLib library is compatible with the
  given version, or a string describing the version mismatch.
  The returned string is owned by GLib and must not be modified
  or freed.

@end deftypefun

@node Second Chapter 
@chapter Second Chapter 

@bye
